### PR TITLE
Merge with Sander

### PR DESCRIPTION
**Pull request by 0xfabi**

### CODE REVIEW

**Comment by svdhoog** [comment]
The changes to `config.yaml` and `plot_config.yaml` in my commit to the master are in order to have more examples. Perhaps we should split this up into two example config folders:

1 config files for tests (the ones shown on the readme.rst page)

2 config files for more complete set of examples -- this is part of the testing of all combinations in issue #20: 
https://github.com/svdhoog/FLAViz/issues/20

Also the results plots for those two sets should be distinguished then:

1 results for tests (like it is now in this repo)

2 results for more complete set of examples

**Comment by 0xfabi** [comment]
I could create a config_full_examples folder which contains your new yaml files.
For developing purposes small config files are better because it is much faster.

**Comment by svdhoog** [comment]
Agreed. The above conflicts would then still need to be resolved on my end, I suspect?
Since I overwrote the original ones?

**Comment by svdhoog** [comment]
I'll try first to replace the results folder in my fork with the new generic names. Then see if the conflict have disappeared.

**Comment by 0xfabi** [comment]
Please just do nothing.
I will merge everything by myself.

For the config files I will create a new folder, ok (config_full_examples)?

**Pull request closed without merging**
